# Generated by Django 5.1.1 on 2024-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_Name", models.CharField(max_length=100)),
                ("last_Name", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=40)),
                ("phone", models.IntegerField()),
                ("Username", models.CharField(max_length=30, unique=True)),
                ("Password", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
