# Generated by Django 5.1.1 on 2024-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="Password",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="Username",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="address",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="first_Name",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="last_Name",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="phone",
        ),
        migrations.AddField(
            model_name="signup",
            name="email",
            field=models.EmailField(default="Email", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signup",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="signup",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="password",
            field=models.CharField(
                default="123", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signup",
            name="first_name",
            field=models.CharField(default="First", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signup",
            name="last_name",
            field=models.CharField(default="Last", max_length=30),
            preserve_default=False,
        ),
    ]
